"use client";

import {
  HandCoins,
  ClipboardList,
  UserCheck,
  Building2,
  Leaf,
  Award,
  Vote,
  Users,
  CloudRain,
  Handshake,
  GraduationCap,
  Ship,
  Database,
  Share2,
  Fingerprint,
  Briefcase,
  TreePine,
  UtensilsCrossed,
  Wallet,
  CircleDollarSign,
  Heart,
  UserPlus,
  GitBranch,
  ShieldCheck,
  MapPin,
  FileCheck,
  FileText,
  Banknote,
  Pill,
  FolderOpen,
  ShoppingCart,
  Target,
  BadgeCheck,
  MessageSquare,
  Truck,
  Archive,
  Eye,
  Headphones,
  Ruler,
  Scale,
  Sun,
  Landmark,
  type LucideIcon,
} from "lucide-react";

const SLUG_TO_ICON: Record<string, LucideIcon> = {
  "aid-disbursement": HandCoins,
  "audit-trails": ClipboardList,
  "benefits-eligibility": UserCheck,
  "business-registry": Building2,
  "carbon-mrv": Leaf,
  "certificates": Award,
  "civic-and-democratic-processes": Vote,
  "civil-registry": Users,
  "climate-and-mrv": CloudRain,
  "consent": Handshake,
  "credentialed-participation": UserCheck,
  "credentials-education": GraduationCap,
  "customs": Ship,
  "data-governance-and-interoperability": Database,
  "data-sharing": Share2,
  "digital-identity-and-credentials": Fingerprint,
  "education-and-workforce": GraduationCap,
  "environmental-registries": TreePine,
  "food-aid": UtensilsCrossed,
  "g2p-payments": Wallet,
  "grants-tracking": CircleDollarSign,
  "health": Heart,
  "humanitarian-ids": UserPlus,
  "inter-agency-coordination": GitBranch,
  "kyc-kyb": ShieldCheck,
  "land-registry": MapPin,
  "licensing": FileCheck,
  "patient-records-pointers": FileText,
  "payments-and-public-finance": Banknote,
  "pharmaceuticals": Pill,
  "portable-records": FolderOpen,
  "procurement-and-invoicing": ShoppingCart,
  "program-integrity": Target,
  "provider-credentialing": BadgeCheck,
  "public-consultations": MessageSquare,
  "public-goods-logistics": Truck,
  "registries-and-records": Archive,
  "selective-disclosure": Eye,
  "service-delivery-and-case-management": Headphones,
  "skills-verification": Award,
  "standards": Ruler,
  "supply-chain-and-logistics": Truck,
  "supply-integrity": Scale,
  "transparency": Sun,
  "treasury-transparency": Landmark,
  "verifiable-credentials": BadgeCheck,
};

const DEFAULT_ICON = Archive;

/** Return the Lucide icon component for a domain slug. */
export function getDomainIcon(slug: string): LucideIcon {
  return SLUG_TO_ICON[slug] ?? DEFAULT_ICON;
}
